In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv('exercise_dataset.csv')
tmp0 = df['130 lb'] / 130
tmp1 = df['155 lb'] / 155
tmp2 = df['180 lb'] / 180
tmp3 = df['205 lb'] / 205
final_rates = (tmp0 + tmp1 + tmp2 + tmp3) / 4

final_rates

0      3.859813
1      1.814897
2      7.264034
3      2.722458
4      3.632627
         ...
243    1.589634
244    1.135966
245    1.361229
246    1.814897
247    1.814897
Length: 248, dtype: float64

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv('exercise_dataset.csv')
tmp0 = df['130 lb'] / 130
tmp1 = df['155 lb'] / 155
tmp2 = df['180 lb'] / 180
tmp3 = df['205 lb'] / 205
final_rates = (tmp0 + tmp1 + tmp2 + tmp3) / 4

df = df.drop(['130 lb', '155 lb', '180 lb', '205 lb', 'Calories per kg'], axis=1) 
df = pd.concat([df, final_rates], axis=1, join='inner')

df

        Activity, Exercise or Sport (1 hour)         0
0                Cycling, mountain bike, bmx  3.859813
1        Cycling, <10 mph, leisure bicycling  1.814897
2                   Cycling, >20 mph, racing  7.264034
3                Cycling, 10-11.9 mph, light  2.722458
4             Cycling, 12-13.9 mph, moderate  3.632627
..                                       ...       ...
243                         General cleaning  1.589634
244                        Cleaning, dusting  1.135966
245                         Taking out trash  1.361229
246            Walking, pushing a wheelchair  1.814897
247  Teach physical education,exercise class  1.814897

[248 rows x 2 columns]

In [25]:
compression_opts = dict(method='zip',
                        archive_name='exercises_with_calories_burned_rate.csv')  
df.to_csv('out.zip', index=False,
          compression=compression_opts)

At this point, additional features were manually added to the item vectors.

In [6]:
df = pd.read_csv('exercises_post_manual_input.csv')

df

,"Activity, Exercise or Sport (1 hour)",Type,Calories Burned per lb (in 60 Min),Intensity,Equipment Required
0,"Cycling, <10 mph, leisure bicycling",Cardio,1.814897,0,1
1,"Cycling, >20 mph, racing",Cardio,7.264034,0,1
2,"Cycling, 10-11.9 mph, light",Cardio,2.722458,0,1
3,"Cycling, 12-13.9 mph, moderate",Cardio,3.632627,0,1
4,"Cycling, 14-15.9 mph, vigorous",Cardio,4.540187,0,1
...,...,...,...,...,...
65,Swimming butterfly,Swimming,4.993856,0,1
66,"Swimming leisurely, not laps",Swimming,2.722458,0,1
67,Swimming sidestroke,Swimming,3.632627,0,1
68,"Swimming, treading water, fast, vigorous",Swimming,4.540187,0,1
69,"Swimming, treading water, moderate",Swimming,1.814897,0,1

In [9]:
col_max = df['Calories Burned per lb (in 60 Min)'].max()
col_min = df['Calories Burned per lb (in 60 Min)'].min()

normalized_rates = (df['Calories Burned per lb (in 60 Min)'] - col_min) / (col_max - col_min)
normalized_rates

0     0.124908
1     0.875061
2     0.249847
3     0.375145
4     0.500084
        ...
65    0.562538
66    0.249847
67    0.375145
68    0.500084
69    0.124908
Name: Calories Burned per lb (in 60 Min), Length: 70, dtype: float64

In [31]:
for index, value in enumerate(normalized_rates):
    if value > 0.66:
        df.loc[index, ('Intensity')] = 2
    elif value > 0.33:
        df.loc[index, ('Intensity')] = 1
    else:
        df.loc[index, ('Intensity')] = 0

df

,"Activity, Exercise or Sport (1 hour)",Type,Calories Burned per lb (in 60 Min),Intensity,Equipment Required
0,"Cycling, <10 mph, leisure bicycling",Cardio,1.814897,0,1
1,"Cycling, >20 mph, racing",Cardio,7.264034,2,1
2,"Cycling, 10-11.9 mph, light",Cardio,2.722458,0,1
3,"Cycling, 12-13.9 mph, moderate",Cardio,3.632627,1,1
4,"Cycling, 14-15.9 mph, vigorous",Cardio,4.540187,1,1
...,...,...,...,...,...
65,Swimming butterfly,Swimming,4.993856,1,1
66,"Swimming leisurely, not laps",Swimming,2.722458,0,1
67,Swimming sidestroke,Swimming,3.632627,1,1
68,"Swimming, treading water, fast, vigorous",Swimming,4.540187,1,1
69,"Swimming, treading water, moderate",Swimming,1.814897,0,1

In [32]:
compression_opts = dict(method='zip',
                        archive_name='exercises_final.csv')  
df.to_csv('out.zip', index=False,
          compression=compression_opts)

Testing Below

In [72]:
df = pd.read_csv('exercises_final.csv')

df

,"Activity, Exercise or Sport (1 hour)",Type,Calories Burned,Intensity,Equipment Required
0,"Cycling, <10 mph, leisure bicycling",Cardio,1.814897,0,1
1,"Cycling, >20 mph, racing",Cardio,7.264034,2,1
2,"Cycling, 10-11.9 mph, light",Cardio,2.722458,0,1
3,"Cycling, 12-13.9 mph, moderate",Cardio,3.632627,1,1
4,"Cycling, 14-15.9 mph, vigorous",Cardio,4.540187,1,1
...,...,...,...,...,...
65,Swimming butterfly,Swimming,4.993856,1,1
66,"Swimming leisurely, not laps",Swimming,2.722458,0,1
67,Swimming sidestroke,Swimming,3.632627,1,1
68,"Swimming, treading water, fast, vigorous",Swimming,4.540187,1,1
69,"Swimming, treading water, moderate",Swimming,1.814897,0,1

In [78]:
df2 = df[(df['Type'] == 'Cardio') | (df['Type'] == 'Calisthenics') | (df['Type'] == 'Strength Training') | (df['Type'] == 'Swimming')]
df2['Calories Burned'] = df2['Calories Burned'] * 150

caloric_distance = abs(df2['Calories Burned'] - 600).rename('Caloric Distance') 
caloric_distance = caloric_distance + (0.7 * np.random.rand(caloric_distance.shape[0]))
df2 = pd.concat([df2, caloric_distance], axis=1)
df2 = df2.sort_values(by=['Caloric Distance']).reset_index(drop=True)

df2.iloc[0].to_dict()

C:\Users\abrah\AppData\Local\Temp\ipykernel_13272\3421678063.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Calories Burned'] = df2['Calories Burned'] * 150

{'Activity, Exercise or Sport (1 hour)': 'Climbing hills, carrying over 42 lb',
 'Type': 'Strength Training',
 'Calories Burned': 612.7359211500001,
 'Intensity': 1,
 'Equipment Required': 1,
 'Caloric Distance': 12.97485247941245}